# Generated by Django 6.0.3 on 2026-03-31 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=datetime.datetime(2026, 3, 31, 16, 59, 42, 197206, tzinfo=datetime.timezone.utc)),
        ),
    ]
